  version: '3.9'
  services:
    db:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      volumes:
        - ~/distributed-cloud/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=root
        - POSTGRES_DB=distributed-cloud
    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: "Li69nux*"
  volumes:
    rabbitmq_data: