// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system-controller.sql

package db

import (
	"context"
)

const deleteSystemController = `-- name: DeleteSystemController :exec
DELETE FROM system_controller
WHERE id = $1
`

func (q *Queries) DeleteSystemController(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSystemController, id)
	return err
}

const getSystemController = `-- name: GetSystemController :one
SELECT id, name, oam_floating, install_file, deploy_file, bootstrap_file, status, admin_pass, created_at FROM system_controller
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSystemController(ctx context.Context, id int32) (SystemController, error) {
	row := q.db.QueryRowContext(ctx, getSystemController, id)
	var i SystemController
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OamFloating,
		&i.InstallFile,
		&i.DeployFile,
		&i.BootstrapFile,
		&i.Status,
		&i.AdminPass,
		&i.CreatedAt,
	)
	return i, err
}
