// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateBiosAttr(ctx context.Context, arg CreateBiosAttrParams) (BiosSetting, error)
	CreateSubcloud(ctx context.Context, arg CreateSubcloudParams) (Subcloud, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNode(ctx context.Context, id int32) error
	// LIMIT $1
	// OFFSET $2;
	DeleteSubcloud(ctx context.Context, id int32) error
	DeleteSystemController(ctx context.Context, id int32) error
	GetBiosAttr(ctx context.Context, id int32) (BiosSetting, error)
	GetNodeById(ctx context.Context, id int32) (Node, error)
	GetSubcloud(ctx context.Context, id int32) (Subcloud, error)
	GetSystemController(ctx context.Context, id int32) (SystemController, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListBiosAttr(ctx context.Context, arg ListBiosAttrParams) ([]BiosSetting, error)
	ListBiosAttrByNodeId(ctx context.Context, nodeID int32) ([]BiosSetting, error)
	ListSubclouds(ctx context.Context) ([]Subcloud, error)
	UpdateNodeProperties(ctx context.Context, arg UpdateNodePropertiesParams) (Node, error)
	UpdateSystemControllerLink(ctx context.Context, arg UpdateSystemControllerLinkParams) (SystemController, error)
	UpdateSystemControllerStatus(ctx context.Context, arg UpdateSystemControllerStatusParams) (SystemController, error)
}

var _ Querier = (*Queries)(nil)
