// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: system-controller.sql

package db

import (
	"context"
)

const deleteSystemController = `-- name: DeleteSystemController :exec
DELETE FROM system_controller
WHERE id = $1
`

func (q *Queries) DeleteSystemController(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSystemController, id)
	return err
}

const getSystemController = `-- name: GetSystemController :one
SELECT id, name, oam_floating, install_file, deploy_file, bootstrap_file, link, status, failed_reason, admin_pass, created_at FROM system_controller
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSystemController(ctx context.Context, id int32) (SystemController, error) {
	row := q.db.QueryRowContext(ctx, getSystemController, id)
	var i SystemController
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OamFloating,
		&i.InstallFile,
		&i.DeployFile,
		&i.BootstrapFile,
		&i.Link,
		&i.Status,
		&i.FailedReason,
		&i.AdminPass,
		&i.CreatedAt,
	)
	return i, err
}

const updateSystemControllerLink = `-- name: UpdateSystemControllerLink :one
UPDATE system_controller
SET link=$2
WHERE id = $1
RETURNING id, name, oam_floating, install_file, deploy_file, bootstrap_file, link, status, failed_reason, admin_pass, created_at
`

type UpdateSystemControllerLinkParams struct {
	ID   int32  `json:"id"`
	Link string `json:"link"`
}

func (q *Queries) UpdateSystemControllerLink(ctx context.Context, arg UpdateSystemControllerLinkParams) (SystemController, error) {
	row := q.db.QueryRowContext(ctx, updateSystemControllerLink, arg.ID, arg.Link)
	var i SystemController
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OamFloating,
		&i.InstallFile,
		&i.DeployFile,
		&i.BootstrapFile,
		&i.Link,
		&i.Status,
		&i.FailedReason,
		&i.AdminPass,
		&i.CreatedAt,
	)
	return i, err
}

const updateSystemControllerStatus = `-- name: UpdateSystemControllerStatus :one
UPDATE system_controller
SET status=$2,
failed_reason=$3
WHERE id = $1
RETURNING id, name, oam_floating, install_file, deploy_file, bootstrap_file, link, status, failed_reason, admin_pass, created_at
`

type UpdateSystemControllerStatusParams struct {
	ID           int32  `json:"id"`
	Status       string `json:"status"`
	FailedReason string `json:"failed_reason"`
}

func (q *Queries) UpdateSystemControllerStatus(ctx context.Context, arg UpdateSystemControllerStatusParams) (SystemController, error) {
	row := q.db.QueryRowContext(ctx, updateSystemControllerStatus, arg.ID, arg.Status, arg.FailedReason)
	var i SystemController
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OamFloating,
		&i.InstallFile,
		&i.DeployFile,
		&i.BootstrapFile,
		&i.Link,
		&i.Status,
		&i.FailedReason,
		&i.AdminPass,
		&i.CreatedAt,
	)
	return i, err
}
