// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type BiosSetting struct {
	ID           int32         `json:"id"`
	NodeID       sql.NullInt32 `json:"node_id"`
	SettingKey   string        `json:"setting_key"`
	SettingValue string        `json:"setting_value"`
	LastUpdated  sql.NullTime  `json:"last_updated"`
}

type Node struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Hostname   string    `json:"hostname"`
	BmIp       string    `json:"bm_ip"`
	BmUser     string    `json:"bm_user"`
	BmPass     string    `json:"bm_pass"`
	Role       string    `json:"role"`
	ParentType string    `json:"parent_type"`
	ParentID   int32     `json:"parent_id"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type NodeAction struct {
	ID         int32          `json:"id"`
	NodeID     sql.NullInt32  `json:"node_id"`
	Action     sql.NullString `json:"action"`
	Status     sql.NullString `json:"status"`
	ExecutedAt sql.NullTime   `json:"executed_at"`
}

type Subcloud struct {
	ID                 int32     `json:"id"`
	Name               string    `json:"name"`
	SystemControllerID int32     `json:"system_controller_id"`
	IpAddress          string    `json:"ip_address"`
	SyncStatus         string    `json:"sync_status"`
	CreatedAt          time.Time `json:"created_at"`
}

type SystemController struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	IpAddress string       `json:"ip_address"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	FullName          string    `json:"full_name"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
