// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateBiosAttr(ctx context.Context, arg CreateBiosAttrParams) (BiosSetting, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateSubcloud(ctx context.Context, arg CreateSubcloudParams) (Subcloud, error)
	CreateSystemController(ctx context.Context, arg CreateSystemControllerParams) (SystemController, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// -- name: UpdateAccount :one
	// UPDATE accounts
	// SET balance=$2
	// WHERE id=$1
	// RETURNING *;
	DeleteNode(ctx context.Context, id int32) error
	// LIMIT $1
	// OFFSET $2;
	DeleteSubcloud(ctx context.Context, id int32) error
	// LIMIT $1
	// OFFSET $2;
	DeleteSystemController(ctx context.Context, id int32) error
	GetBiosAttr(ctx context.Context, id int32) (BiosSetting, error)
	GetNodeById(ctx context.Context, id int32) (Node, error)
	GetSubcloud(ctx context.Context, id int32) (Subcloud, error)
	GetSystemController(ctx context.Context, id int32) (SystemController, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListBiosAttr(ctx context.Context, arg ListBiosAttrParams) ([]BiosSetting, error)
	ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error)
	ListSubclouds(ctx context.Context) ([]Subcloud, error)
	ListSystemController(ctx context.Context) ([]SystemController, error)
	UpdateSystemControllerInventory(ctx context.Context, arg UpdateSystemControllerInventoryParams) (SystemController, error)
}

var _ Querier = (*Queries)(nil)
